### PR TITLE
Reduce logging output when things are OK

### PR DESCRIPTION
**Pull request by jeremyw**
Follow the Rule of Silence to keep the signal-noise ratio high in logs.

### CODE REVIEW

**Review by youvalv — APPROVED** [review]
Thanks for this @jeremyw! that's one rule we should have followed :) 

I'll approve and merge

**Comment by jeremyw** [comment]
Thanks @youvalv! I didn't mean for that come across as so demanding 😅

**Comment by youvalv** [comment]
Lol @jeremyw, not at all :)
thanks for using sourcebit!

What are you building with it BTW?

**Comment by jeremyw** [comment]
@youvalv We're using sourcebit to integrate Contentful with our signup flow at [Form Health](https:///www.formhealth.co), a telehealth service for the treatment of obesity. Works great in our SSG pipeline!

**Comment by youvalv** [comment]
Amazing! thanks for sharing :)

**Pull request merged**
